### ISSUE TITLE
Build fails (missing junit jar?)

### ISSUE THREAD

**Issue by cowtowncoder** [Karmasphere/lzo-java#1]
When trying to build newly cloned instance, I get compilation errors that suggest that junit jar might not be included under lib (or Ant compile path).

**Comment by shevek** [comment]
This is something to do with having (or not having) netbeans installed, I think the build file is being too clever. If you run "ant jar", you should get a jar file just fine. All my machines have netbeans, so I can't reproduce, but I will try to work it out. In the meantime, please use "ant jar" as a workaround.

**Comment by shevek** [comment]
Please see if 838bea5 fixes this. Thank you.
